language: node_js
node_js:
- 12
script:
- npm run client-install
- npm test
- npm run client-test
deploy:
  provider: heroku
  api_key:
    secure: bqvkSqMrG9jzxJBImLFwMZ2zxuqy99dn8+48adzo+MeMBECD7RQdPFFvOwSGaSTvLBv9qSucYQf5pvLzcqRkOhbUAi0XfFJEnYekh/by67/R3UZKWBOKvKEXaaXSRvQEgk+ZETBIpHSsE+fzJTAM1JtqbHPjLiQLfppgr7myT6N/7ku8AkE74FTaRyh9NPPQvtpxP1lXBWgExD9JoPic/egb3IbxIB/wNKjSheEtBuRnaWP5RMYwYeKMndU1DwDoFtG7AnsyZN402s87JioIuOUgRqgnKLxCmRZYLoVAh7y24oN/2nmIUZTNu70FdMcI9sCwN3bWjNN5tWopNxuhh2wqxeTPESjBs59octzITmC3hbA6NUjp2flOtihrErBY4FOjUJRg2nd8chMLma8+i5u4ZQOo0qyIB87iku2tqhe4VfFNdQlKEH1rQo9Q8wcL/uKYPg7WuGMjhqBmJ7tStlA0+y8FiOU1oM853GZZNZsRqAsd1YEvFjgiAjb68u449fvG+5JOIebdkFolSZp9atfrWlmNCOYRYLDH8kwNnPtjnc42BMMyQ+8zcqR/euP/WMiYrhNjM0QV4xwzk9Vo8yxGYpD7XAcgkF4XDu8OV+R9dCZNyfhkyIsw+Tk7ziIompZym3lHbPCAN7LHeYZh/r1+6GFUXTkQhGSCLXBYZgA=
  app: shrouded-river-59487
